### ISSUE TITLE
Weapon Bug

### ISSUE THREAD

**Issue by Anjuts** [Eastrall/Rhisis#236]
dual weapon on character select. but in game just one handed.
![dual](https://user-images.githubusercontent.com/13416489/58858504-3b749780-86da-11e9-9934-7975577b14f2.png)

**Comment by Eastrall** [comment]
Thanks for the bug report. I tagged the issue as a bug and I will investigate the problem and make a fix.

**Comment by Eastrall** [comment]
Can you explain how you did to make this bug happen ? Step by step ? Equip a weapon, then unequip and equip again ? This will help me figure out what is wrong. Thank you.

**Comment by Anjuts** [comment]
I just switch a new weapon and this happens after I relogin. My main weapon is the white one. and when im dragging to left weapon there is a weapon equipped invisible but cant unequip.

**Comment by Eastrall** [comment]
After investigating the issue, the problem is related to Entity Framework Core, which has a tracking mechanism on entities. When we request the list for the first time, everything goes well, but when you log out, the entity is still behing tracked by EFCore and is not updated correctly when saving the player.

I have found a fix, which would be to dispose the database connection each time we use it. 
It is actually recommended to dispose the database context and have a context per handler, this will reduce risks of entities behing tracked at the same time in a multi-threaded environment.
