### ISSUE TITLE
Buffs attributes are only visible after relog

### ISSUE THREAD

**Issue by SvenLlama** [Eastrall/Rhisis#485]
# :beetle: Bug Report

**Rhisis version:** latest develop branch

## Expected Behavior
The extra attributes such as STR/STA are immediately visible in the client after casting a buff.

## Current Behavior
After casting a assist buff (beef up, mental sign etc) the stats are only increased after relogging.

## Steps to Reproduce

1. log in 
2. buff yourself
3. notice the character screen doesn't show increased attributes
4. relog
5. the character screen now shows the correct attribute amount

## Detailed Description

The _Attributes#Increase_ is triggered, which triggers the _UpdateParamPointSnapshot_ to be sent, but this doesn't seem to update the client information.

**Comment by Eastrall** [comment]
After investigating the issue, it seems that the `AttributeSystem` is using the `SNAPSHOTTYPE_SETPOINTPARAM` packet instead of the `SNAPSHOTTYPE_SETDESTPARAM` packet.

The `SNAPSHOTTYPE_SETPOINTPARAM` is only used for point parameters like `HP`, `MP`, Gold, and others. All other attributes like `STR`, `STA`, etc... should use the `SNAPSHOTTYPE_SETDESTPARAM` packet.
